college/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :teachers do
    resources :pictures, module: :teachers
  end
  resources :students  do
    resources :pictures, module: :students
    member do
      patch 'assign' 
      get 'unassign'
    end
  end
  devise_for :users
  root 'students#index'

end

college/app/models/teacher.rb
class Teacher < ActiveRecord::Base
	# has_attached_file :image
	# validates_attachment :image, presence: true,
	# 					  content_type: { content_type: "image/jpeg" },
	# 					  size: { in: 0..100.kilobytes }
  	has_and_belongs_to_many :students
  	has_many :pictures, as: :imageable, dependent: :destroy
  	accepts_nested_attributes_for :pictures
  	# has_many :subjects
  	# has_many :students, through: :subjects
end

college/app/controllers/teachers/pictures_controller.rb
class Teacher::PicturesController < PicturesController
	before_action :set_imageable
	private
	def set_imageable
		@imageable = Teacher.find(params[:teacher_id])
	end
 end

college/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all.order(name: :ASC).paginate(page: params[:page], per_page: 5)
    render locals: {
      teachers: @teachers
    } 
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    render locals: {
      teacher: Teacher.find_by!(id: params[:id])
    }
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        
        teacher_picture = @teacher.pictures.new("name" => picture_params)
        teacher_picture.save
        upload

        format.html { redirect_to @teacher, notice: 'Teacher Record is Successfully Created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)

        imageable = set_teacher
        teacher_picture = imageable.pictures.new(picture_params)
        teacher_picture.save
        upload
        
        format.html { redirect_to @teacher, notice: 'Teacher Record is Successfully Updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher Record is Successfully Destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find_by!(params[:id])
    rescue
      record_not_found
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :description)
    end

    

    def picture_params
      image = params.require(:teacher).permit(:image)['image'].original_filename
    end

    def upload
      uploaded_io = params[:teacher][:image]
      File.open(Rails.root.join('app','assets','images',uploaded_io.original_filename),'wb') do |file|
        file.write(uploaded_io.read)
      end
    end

    def record_not_found
      render plain: "404 Not Found", status: 404
    end

    
end

college/app/helpers/teachers_helper.rb
module TeachersHelper
end

college/app/views/teachers/_form.html.erb
<div class="section">
  <%= form_for teacher, html: { multipart: true } do |f| %>
  
   <div class="field" style="width: 50%;">
    <div class="control">
      <%= f.label :name, class: 'label' %>
      <%= f.text_field :name,class: 'input', wrapper: false  %>
    </div>
  </div>
  <div class="field" style="width: 50%;">
    <div class="control">
      <%= f.label :description, class: 'label' %>
      <%= f.cktext_area :description, class: 'textarea', wrapper: false  %>
    </div>
  </div>
  
  <div class="field" style="width: 50%;">
    <div class="control">
      <%= f.label :image, class: 'label' %>
      <%= f.file_field :image, class: 'input', wrapper: false  %>
    </div>
  </div>
  
  <%= f.submit :Save, class: "button is-primary" %> 
  <% end %>
</div>


  

college/app/views/teachers/_image.html.erb
<%= form_for ([imageable, Picture.new]) do |f| %>
	<div class="form-group">
		<%= f.file_field :picture, class: 'form-control' %>	
	</div>
	<%=  f.submit class: 'btn btn-primary' %>

<% end %>

college/app/views/teachers/_teacher.html.erb
<div class="box" style="width: 60%;">
	<article class="media">
		<div class="media-content">
			<div class="content">
				<%= teacher.name  %>
				
			</div>
		</div>
		<div>
			<% if user_signed_in? %>
			<%= link_to 'Un-Assign', { controller: 'students', action: 'unassign', teacher: teacher.id}, class: "button is-danger", data: { confirm: "Are you sure?"}  %>
		<% end %>	
		</div>
		
	</article>
</div>

college/app/views/teachers/edit.html.erb
<div style="margin-left: 20%;">
	<h1>Editing Teacher</h1>

	<%= render 'form', teacher: @teacher%>
	<%= link_to 'Show', @teacher %> |
	<%= link_to 'Back', teachers_path %>	

</div>

college/app/views/teachers/index.html.erb
<% content_for :page_title, "Teachers" %>

<section class="section">
  <div class="container" style="width: 60%;">
    <span style="margin-left: 2%; font-size: 25px;font-weight: bold;">Teacher List</span>
    <% teachers.each do |teacher| %>
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4">
              <%= link_to teacher.name, teacher %>
            </p>
          </div>
        </div>
        <div class="content">
          <%= %>
        </div>
      </div>
    </div>
  <% end %>
    <div style="margin-top: 2%;">
      <%= will_paginate teachers, renderer: BulmaPagination::Rails  %>  
    </div>
  </div>
</section>

college/app/views/teachers/new.html.erb
<div style="margin-left: 20%;">
	<h1>New Teacher</h1>

	<%= render 'form', teacher: @teacher %>

	<%= link_to 'Back', teachers_path %>
</div>

college/app/views/teachers/show.html.erb
<% content_for :page_title %>

<section class="section">
	<div class="container" style="width: 60%;">
		<nav class="level">
			<div class="level-left">
				<span style="font-weight: bold; font-size: 30px;"><%= teacher.name %></span>
			</div>
		
			<div class="level-right">
				<p class="level-item">
					<%= link_to "Edit",edit_teacher_path(teacher),class: "button" %>

				</p>
				<p class="level-item">
					<%= link_to 'Delete', teacher_path(teacher), method: :delete, data: { confirm: "Are you sure?"}, class: "button is-danger " %>
				</p>
			</div>
			

		</nav>
		<hr />
		<nav class="level">
			<div class="content" style="float: left;">
				<p><h5>Name :</h5><%= teacher.name %></p>
				<p><h5>Description :</h5><%= raw teacher.description %></p>
			</div>

			<div style="float: right; margin: 2%; ">
				<% teacher.pictures.each do |image| %>
				<%= image_tag image.name, height: '200px', width: '200px' %>
				<% end %>
			</div>
		
		</nav>
			<hr />
		
		<nav class="level">
			<!-- <span style="font-weight: bold; font-size: 20px;">Associated Teachers</span> -->
			<div class="content"></div>
			<section class="section">
				<div class="container">
					<h5 class="subtitle is-4">Associated Students</h5>
					<h2 class="subtitle is-5">
						<strong><%= teacher.students.count %></strong> Students
					</h2>
					<%= render teacher.students, teacher: teacher %>
				</div>
			</section>
		</nav>
		
</section>