college/config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :teachers do
    resources :pictures, module: :teachers
  end
  resources :students  do
    resources :pictures, module: :students
    member do
      patch 'assign' 
      get 'unassign'
    end
  end
  devise_for :users
  root 'students#index'

end

college/app/models/student.rb
class Student < ActiveRecord::Base
	validates :registration_number, presence: true
	validates :name, presence: true
	validates :branch, presence: true
	# has_attached_file :image
	# validates_attachment :image, presence: true,
	# 					  content_type: { content_type: "image/jpeg" },
	# 					  size: { in: 0..100.kilobytes }
	has_and_belongs_to_many :teachers
	has_many :pictures, as: :imageable, dependent: :destroy
	accepts_nested_attributes_for :pictures#, attachment: :file
	# has_many :subjects
	# has_many :teachers, through: :subjects
end

college/app/controllers/students/pictures_controller.rb
class Student::PicturesController < PicturesController
	before_action :set_imageable
	private
	def set_imageable
		@imageable = Student.find(params[:student_id])
	end
end 

college/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :assign]
  before_action :authenticate_user!, except: [:index, :show]

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  
  # GET /students
  # GET /students.json
  def index
    @students = Student.all.order(registration_number: :ASC).paginate(page: params[:page], per_page: 5)
    render locals: {
      students: @students
    } 
  end

  # GET /students/1
  # GET /students/1.json
  def show
    render locals: {
      student: Student.find_by!(id: params[:id])
    }
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        
        student_picture = @student.pictures.new("name" => picture_params)
        student_picture.save
        upload
        format.html { redirect_to @student, notice: 'Student Record is Successfully Created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        
        format.html { redirect_to @student, notice: 'Student Record Is Successfully Updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student Record Is Successfully Destroyed.' }
      format.json { head :no_content }
    end
  end

  def assign

    #   @student.teachers << Teacher.find(params[:student][:id])
      # st = assign_teacher
      if(assign_teacher.nil?)
           redirect_to @student, alert: 'Teacher Is Already Assigned To This Student'
      else
          @student_teacher = StudentsTeacher.new(assign_teacher)
          if @student_teacher.save
            redirect_to @student, notice: 'Teacher Is Successfully Assigned To This Student' 
          else
            render 'show'
          end
      end
  end

  def unassign
    StudentsTeacher.where(teacher_id: params['teacher'], student_id: params['id'] ).take.destroy
    respond_to do |format|
      format.html { redirect_to student_path, notice: 'Assignment Is Successfully Removed.' }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find_by_id!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:registration_number, :name, :branch)
    end

    def upload
      uploaded_io = params[:student][:image]
      File.open(Rails.root.join('app','assets','images',uploaded_io.original_filename),'wb') do |file|
        file.write(uploaded_io.read)
      end
    end

    def picture_params
      image = params.require(:student).permit(:image)['image'].original_filename
    end

    def assign_teacher
      student_teacher = StudentsTeacher.where(teacher_id: teacher_params, student_id: @student.id ).take
      if student_teacher.nil?
        return {"teacher_id" => teacher_params, "student_id" => @student.id}
      else
        nil
      end
      # byebug
    end

    def teacher_params
      params.require(:student).permit(:id)['id']
      
    end

    def record_not_found
      render plain: "404 Not Found", status: 404
    end

end

college/app/helpers/students_helper.rb
module StudentsHelper
end

college/app/views/students/_assign.html.erb
  <%= form_for student, url: {action: "assign" } do |f| %>

  <div class="field" style="width: 50%;">
    <div class="control">
      <%= f.label :Teachers, class: 'label' %>
      <%= f.collection_select :id, Teacher.order(:name),:id,:name, {}, class: 'select is-medium', multiple: false %>
    </div>
  </div>
  	<%= f.submit :Save, class: "button is-primary" %>
  <% end %>
</div>

college/app/views/students/_form.html.erb
<div class="section">
  <%= form_for student, html: { multipart: true } do |f| %>

  <% if student.errors.any? %>
    <div id="error_explanation" class="alert" style="text-align: center; color: red;">
      <h2><%= pluralize(student.errors.count, "error") %> Prohibited this record from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field" style="width: 50%;">
    <div class="control">
      <%= f.label :registration_number, class: 'label', wrapper: false %>
      <%= f.text_field :registration_number, class: 'input', wrapper: false %>
    </div>
  </div>
  <div class="field" style="width: 50%;">
    <div class="control">
      <%= f.label :name, class: 'label' %>
      <%= f.text_field :name,class: 'input', wrapper: false  %>
    </div>
  </div>
  
  <div class="field" style="width: 50%;">
    <div class="control">
      <%= f.label :branch, class: 'label' %>
      <%= f.text_field :branch, class: 'input', wrapper: false  %>
    </div>
  </div>
  
  <div class="field" style="width: 50%;">
    <div class="control">
      <%= f.label :image, class: 'label' %>
      <%= f.file_field :image, class: 'input', wrapper: false  %>
    </div>
    
    <!-- <div class="field" style="width: 50%;">
      <div class="control">
        <%= f.label :'Assign Teacher', class: 'label' %>
        <%= f.collection_select :id, Teacher.order(:name),:id,:name, include_blank: false, class: 'input' %>
      </div>
    </div> -->
  </div>
  
  <%= f.submit :Save, class: "button is-primary" %>
  <% end %>
</div>


  

college/app/views/students/_image.html.erb
<%= form_for ([imageable, Picture.new]) do |f| %>
	<div class="form-group">
		<%= f.file_field :picture, class: 'form-control' %>	
	</div>
	<%=  f.submit class: 'btn btn-primary' %>

<% end %>

college/app/views/students/_student.html.erb
<div class="box" style="width: 60%;">
	<%= student.name  %>
</div>

college/app/views/students/edit.html.erb
<div style="margin-left: 20%;">
	<h1>Editing Student</h1>

	<%= render 'form', student: @student %>
	<%= link_to 'Show', @student %> |
	<%= link_to 'Back', students_path %>	

</div>

college/app/views/students/index.html.erb
<% content_for :page_title, "Students" %>

<section class="section">
  <div class="container" style="width: 60%;">
    <span style="margin-left: 2%; font-size: 25px;font-weight: bold;">Student List</span>
    <% students.each do |student| %>
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4">
              <%= link_to student.name, student %>
            </p>
          </div>
        </div>
        
      </div>
    </div>

  <% end %>
  <div style="margin-top: 2%;">
  <%= will_paginate students, renderer: BulmaPagination::Rails  %>  
</div>
  </div>
            
</section>

      






<!-- <p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Registration number</th>
      <th>Name</th>
      <th>Branch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.registration_number %></td>
        <td><%= student.name %></td>
        <td><%= student.branch %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>
 -->

college/app/views/students/new.html.erb
<div style="margin-left: 20%;">
	<h1>New Student</h1>

	<%= render 'form', student: @student %>

	<%= link_to 'Back', students_path %>
</div>

college/app/views/students/show.html.erb
<% content_for :page_title %>

<section class="section">
	<div class="container" style="width: 60%;">
		<nav class="level">
			<div class="level-left">
				<span style="font-weight: bold; font-size: 30px;"><%= student.name %></span>
			</div>
		
			<div class="level-right">
				<p class="level-item">
					<%= link_to "Edit",edit_student_path(student),class: "button" %>

				</p>
				<p class="level-item">
					<%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: "Are you sure?"}, class: "button is-danger " %>
				</p>
			</div>
			

		</nav>
		<hr />
		<nav class="level">
			<div class="content" style="float: left;">
				<p><h5>Registration Number :</h5><%= student.registration_number %></p>
				<!-- <p><h5>Name :</h5><%= @student.name %></p> -->
				<p><h5>Branch :</h5><%= student.branch %></p>
			</div>

			<div class="content" style="float: right; margin: 2%; ">
				<% student.pictures.each do |image| %>
				<%= image_tag image.name, height: '200px', width: '200px' %>
				<% end %>
			</div>
		</nav>
		<hr />
		<nav class="level">
			<!-- <span style="font-weight: bold; font-size: 20px;">Associated Teachers</span> -->
			<div class="content"></div>
			<section class="section">
				<div class="container">
					<h5 class="subtitle is-4">Associated Teachers</h5>
					<h2 class="subtitle is-5">
						<strong><%= student.teachers.count %></strong> Teachers
					</h2>
					<%= render student.teachers, student: student%>
					
				</div>
			</section>
			
		</nav>
	</div>
	<section class="section" style="margin-left: 20%; margin-top: -5%;">
		<div class="container">
			Assing Teacher
			<%= render 'students/assign', student: student%>
		</div>
	</section>

</section>